### ISSUE TITLE
Irreversible damage to Clash Royale

### ISSUE THREAD

**Issue by p999x** [dtcalabro/iOSSecuritySuiteBypass#1]
I’m pretty sure it is reversible by restoring the phone or erasing it but for some reason Clash Royale now doesn’t want to open, I’m sure it started after installing this tweak because this was the first app i opened.

Even rebooting and reinstalling/erasing app data doesn’t fix it, not even in unjailbroken state.
iPhone 13
iOS 16.3.1 (20D67)
JB: Dopamine 2.0.5

**Comment by dtcalabro** [comment]
I'm sorry to hear that, but that seems very odd for my tweak to have caused such an issue. I'd like to ask a few more follow up questions first to make sure we're on the same page.

1.) What app is using the iOSSecuritySuite library that you were aiming to bypass?
2.) Are you positive that my tweak is the issue? I'm only asking because I find it extremely hard to believe that my tweak would cause such an issue even in a non-jailbroken state as my tweak only injects into apps which use the library it targets and therefore would not work in a non-jailbroken state.

**Comment by p999x** [comment]
tbh i find it extremely rare. I reviewed the tweak's code and there's nothing able to mess one app this bad. Must be a very very inusual coincidence. The thing is that no more cr in this phone i guess.
Another thing I found inusual was that clash royale is not making any crash logs, not even preferences app or krashkop.
